### ISSUE TITLE
Implementing Digest trait to help with generic usage

### ISSUE THREAD

**Issue by nyurik** [servo/rust-fnv#32]
The [digest crate](https://crates.io/crates/digest) offers a number of traits to treat all hashers in a generic way.  Since FNV is not a crypto-secure hasher, it was understandably [rejected](https://github.com/RustCrypto/hashes/issues/380) by the `RustCrypto/hashes` project.  Yet, I think there is a lot of value to support the same digest traits as other hashers to make it possible to write simple generic code that supports multiple hashers.  For example, my `nyurik/sqlite-hashes` crate uses [common code](https://github.com/nyurik/sqlite-hashes/blob/28f5ffe779cd6962bbe12a5ca6cf56ccf6cb3a96/src/scalar.rs#L48) to support several hashing algorithms thanks to this consistency, but I would have to do a lot of custom code to [support FNV](https://github.com/nyurik/sqlite-hashes/issues/6).

I would like to propose adding a feature-gated `digest` that would allow FNV to be used as a `<T: NamedDigest + Clone + UnwindSafe + RefUnwindSafe + 'static>` type.

cc: @HindrikStegenga

**Comment by Manishearth** [comment]
Hm. I'm not sure. The trait says "Convenience wrapper trait covering functionality of cryptographic hash functions with fixed output size.", and it seems like a violation of its guarantees. I'm not fully opposed but I don't think it's a good precedent to ignore the crate intent this way.

Feels like `digest` should ideally be split into a `Digest` and `HashFunction` or something with the former having cryptographic properties, and the latter having all the functions.

**Comment by Manishearth** [comment]
Yes, if they decide to make the trait not just about cryptographic hashes, I'd be fine with it. I do not want to deal with the issue where someone uses `: Digest` bound in a way that relies on the cryptographic nature of the hash. I don't understand their users and don't want to muddy the water their, this is a call they should make.

**Comment by nyurik** [comment]
I understand your concern with the wording. My only take on all this is that without a common trait pattern, anyone that wants to support multiple hash algorithms in their code cannot do so without considerable extra code, regardless if the algo is secure cryptographically at the moment, used to be secure, or never was secure at all.

That's why I thought it would make sense to have it as an optional feature-flag-gated feature, and possibly with a clear statement that it does NOT claim to be cryptograhically secure, but does provide the same common hashing interface for a fixed-sized hash generation.

**Comment by nyurik** [comment]
I have written a simple wrapper for all such cases called [noncrypto-digests](https://crates.io/crates/noncrypto-digests). For now it just implements Fnv, but eventually I plan to add all other ones like CRC32 and the like.

**Comment by nyurik** [comment]
P.S. I was surprised that there is no `Clone` implemented for the `Hasher`. Is this by design? I worked around it with the `FnvHasher::with_key(hasher.finish())`, but that feels like a hack.

**Comment by nyurik** [comment]
Thx @Manishearth, implemented in https://github.com/servo/rust-fnv/pull/33
